# golangci-lint v2 configuration
# See: https://golangci-lint.run/usage/configuration/

version: "2"

linters:
  default: standard
  enable:
    - dupl           # Detect duplicate code
    - goconst        # Find repeated strings that could be constants
    - gocyclo        # Check cyclomatic complexity
    - gosec          # Security checks
    - misspell       # Spelling mistakes
    - unconvert      # Unnecessary type conversions
    - revive         # Go style linter

linters-settings:
  dupl:
    threshold: 100
  goconst:
    min-len: 3
    min-occurrences: 3
  gocyclo:
    min-complexity: 15

formatters:
  enable:
    - gofmt
    - goimports

run:
  timeout: 5m
