#!/bin/bash
# Setup cron jobs for automated backups

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CRON_FILE="/etc/cron.d/trading-engine-backup"

echo "Setting up backup cron jobs..."

# Create cron file
cat > "$CRON_FILE" <<'EOF'
# Trading Engine Backup Cron Jobs
# Auto-generated by setup-cron.sh

SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
BACKUP_CONFIG=/opt/trading-engine/scripts/backup/backup.config

# Full backup daily at 2 AM
0 2 * * * root /opt/trading-engine/scripts/backup/backup-full.sh >> /var/log/trading-engine/backup/cron.log 2>&1

# Incremental backup every 4 hours
0 */4 * * * root /opt/trading-engine/scripts/backup/backup-incremental.sh >> /var/log/trading-engine/backup/cron.log 2>&1

# Verify backups daily at 3 AM
0 3 * * * root /opt/trading-engine/scripts/backup/run-verification.sh >> /var/log/trading-engine/backup/cron.log 2>&1

# Cleanup old backups daily at 4 AM
0 4 * * * root /opt/trading-engine/scripts/backup/cleanup-old-backups.sh >> /var/log/trading-engine/backup/cron.log 2>&1

# Health check every hour
0 * * * * root /opt/trading-engine/scripts/backup/backup-health-check.sh >> /var/log/trading-engine/backup/cron.log 2>&1

# Disaster recovery test monthly (first Sunday at 5 AM)
0 5 * * 0 root [ $(date +\%d) -le 7 ] && /opt/trading-engine/scripts/backup/dr-test.sh >> /var/log/trading-engine/backup/cron.log 2>&1
EOF

# Set permissions
chmod 644 "$CRON_FILE"

echo "✓ Cron jobs installed: $CRON_FILE"
echo ""
echo "Backup schedule:"
echo "- Full backup:        Daily at 2:00 AM"
echo "- Incremental backup: Every 4 hours"
echo "- Verification:       Daily at 3:00 AM"
echo "- Cleanup:            Daily at 4:00 AM"
echo "- Health check:       Hourly"
echo "- DR test:            Monthly (first Sunday at 5:00 AM)"
echo ""
echo "View cron logs: tail -f /var/log/trading-engine/backup/cron.log"

# Restart cron service
if command -v systemctl >/dev/null 2>&1; then
    systemctl restart cron 2>/dev/null || systemctl restart crond 2>/dev/null || true
    echo "✓ Cron service restarted"
fi

exit 0
